version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: zakharov98/sensors-backend
    restart: always
    ports:
      - "${API_PORT:-3000}:3000"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: "hydra"
    ports:
      - "${ADMINER_PORT:-8080}:8080"

volumes: 
     pgdata: