version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: "hydra"
    ports:
      - "${ADMINER_PORT:-8080}:8080"

volumes: 
     pgdata: