version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: sensors-backend
    image: zakharov98/sensors-backend
    restart: always
    ports:
      - "${API_PORT:-3004}:3004"
    depends_on:
      - "db"

networks:
  default:
    external:
      name: neuromaps-network

volumes: 
     pgdata: